session_name: dev
shell_command_before:
  - echo "Iniciando ambiente de desenvolvimento..."
  - cd ~/dotfiles
windows:
  - window_name: editor
    # Começamos com apenas um painel que inicia o zsh
    panes:
      # Se for usar o caminho completo, não pode usar atalhos como $HOME ou ~/
      - shell_command: "bash ./tmux/layout.sh"
  - window_name: navegador
    panes:
      - shell_command: firefox
